version: "3.8"

services:
  grocy:
    image: digikwal/grocy-fpm:v1.0.0
    ports:
      - "8080:9000"
    volumes:
      - grocy_data:/var/www/html/data
    restart: unless-stopped

volumes:
  grocy_data:
