# .github/workflows/release-trigger.yml

name: Release Trigger

on:
  push:
    branches:
      - main

jobs:
  wait:
    uses: ./.github/workflows/wait-for-check.yml
    with:
      sha: ${{ github.sha }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}